### ISSUE TITLE
install / run in a Windows environment

### ISSUE THREAD

**Issue by nnako** [asciimoo/drawille#31]
I'd like to use `drawille` on a Windows operating system (Windows 7 or 10). After successfully installing the `drawille` package into my virtual environment, using `pip`, using it by typing

``` python
>>> from drawille import Canvas
```

leads to this error:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nnako\ENV__Python27\lib\site-packages\drawille.py", line 23, in <module>
    import curses
  File "C:\PROGS\Python__v2_7_9\Lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
```

So, it seems, there is a dependency on the `curses` package and Windows doesn't provide the package, natively. So I installed `curses` using the instructions from [this StackOverflow post](http://stackoverflow.com/questions/32417379/what-is-needed-for-curses-in-python-3-4-on-windows7). But when I now enter my python installation and enter the following lines:

``` python
>>> from drawille import Canvas
>>> c=Canvas()
>>> c.set(10,10)
>>> print(c.frame())
```

the result on screen is:

```Ôáä```

and not a dot as expected (and as I see when using my Linux computer and the same lines of code).

Any hints?

**Comment by pwab** [comment]
I can confirm this problem in parts so I'll try to provide as much information as possible:

## My machine

Windows 7 x64
Python v3.6.1 on win32

## Python stuff

- Installed drawille with `pip install drawille`
- Get the `ImportError: No module named _curses` when trying to import the module
- Installed `curses‑2.2‑cp36‑cp36m‑win32.whl` from [pythonlibs](https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses)
- No error anymore but different output in different console-applications (and different font-settings)

## Testcode

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
from drawille import Canvas
from math import sin, radians

c = Canvas()

for x in range(0, 1800, 10):
    c.set(x / 10, 10 + sin(radians(x)) * 10)

print(c.frame())
```

## Output

### cmd.exe
![cmd_2017-11-03_11-30-14](https://user-images.githubusercontent.com/19271185/32369890-5c555186-c08b-11e7-87d8-725f6af28a2f.png)

### powershell
![powershell_2017-11-03_11-33-02](https://user-images.githubusercontent.com/19271185/32369892-6012059e-c08b-11e7-8b81-2aa7bb7df834.png)

### conemu
![conemu64_2017-11-03_11-34-25](https://user-images.githubusercontent.com/19271185/32369902-645cd890-c08b-11e7-8d41-1da74ac3d924.png)

## Conclusion

I'm not sure how this depends on font-settings but with [conemu](https://conemu.github.io/) (which has a better font- and encoding-support than the other ones) it works fine.

**Comment by sztomi** [comment]
I can confirm that this also works in the new Windows Terminal app 

![image](https://user-images.githubusercontent.com/240594/62860091-62b19b80-bcff-11e9-8ca8-1713dbcdc767.png)
