### ISSUE TITLE
ImportError: cannot import name Canvas - Python 3.7 on MacOS BigSur

### ISSUE THREAD

**Issue by McNugget6750** [asciimoo/drawille#51]
After successfully installing using the pip command using python3.7, I try running any of the examples.
However, I get a Canvas not found error immediately.

```
$python drawille.py
Traceback (most recent call last):
  File "drawille.py", line 5, in <module>
    from drawille import Canvas
  File "/Users/*********/repos/drawille/drawille.py", line 5, in <module>
    from drawille import Canvas
ImportError: cannot import name Canvas
```

```
$python3 drawille.py
Traceback (most recent call last):
  File "drawille.py", line 5, in <module>
    from drawille import Canvas
  File "/Users/*********/repos/thermal_testing/drawille.py", line 5, in <module>
    from drawille import Canvas
ImportError: cannot import name 'Canvas' from partially initialized module 'drawille' (most likely due to a circular import) (/Users/*********/repos/thermal_testing/drawille.py)
```

**Comment by Christinele14** [comment]
How about setting the path to your canvas package and retrying with "import canvas" (Do not use capital C).
I met a similar issue with canvas and could fix it now. Hopefully, it could help you.
