### ISSUE TITLE
AttributeError: tobytes

### ISSUE THREAD

**Issue by bergonzzi** [asciimoo/drawille#9]
I have Python 2.7.5 on Mac OSX Mavericks with PIL 1.1.7 and I get the following when running the xkcd.py example:

```
Traceback (most recent call last):
  File "xkcd.py", line 66, in <module>
    for pix in i.tobytes():
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: tobytes
```

I was able to fix it by changing line 66 from:

```
for pix in i.tobytes():
```

to

```
for pix in i.tostring():
```

I found it with some help from [this stackoverflow question](http://stackoverflow.com/questions/10854903/what-is-causing-dimension-dependent-attributeerror-in-pil-fromarray-function). It seems like the official PIL 1.1.7 still uses the tostring method while Pillow is deprecating it in favor of tobytes (although it still supports the old one).

A simple approach to deal with this could be to just test the attribute first:

```
   try:
        i_converted = i.tobytes()
    except AttributeError:
        i_converted = i.tostring()

    for pix in i_converted:
    (...)
```

**Comment by noraj1337** [comment]
tobytes doesn't work with : 
PIL==1.1.7
Pillow==3.4.1

```
>>> qr.decode("qrcode.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noraj/.local/lib/python2.7/site-packages/qrtools/qrtools.py", line 164, in decode
    raw = pil.tobytes()
  File "/home/noraj/.local/lib/python2.7/site-packages/PIL/Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: tobytes
```
